import React, { useState, useEffect } from "react";

const AiPolliAnimals = ({name}) => {




    

        const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(name)}`;

      
   
    
    return (
        <div className="mainBook">
           
            <br />
         

            {imageUrl && (
                <div style={{ marginTop: "20px" }}>
                    <img
                        src={imageUrl}
                        alt="Generated"
                        style={{ maxWidth: "100%", borderRadius: "8px" }}
                    />
                </div>
            )}
            <p>The image is just an illustration, generated by AI.</p>
        </div>
    );
}
export default AiPolliAnimals;

